-- ============================================================
-- Supabase Schema  |  Online Equipment Borrowing & Return
-- Monitoring System  |  SAD-EquipmentBorrowing-Moreno
-- Upgraded with Lab 4 Section B Requirements
-- Run this in: Supabase Dashboard > SQL Editor > New query
-- ============================================================

-- ---------- PROFILES / ROLES (Borrower, Officer, Administrator) ----------
CREATE TABLE IF NOT EXISTS public.profiles (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL DEFAULT 'borrower'
             CHECK (role IN ('borrower', 'officer', 'administrator')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Upgrade existing constraint if present
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('borrower', 'officer', 'administrator'));

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_authed" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own"   ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own"   ON public.profiles;

CREATE POLICY "profiles_select_authed" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;

-- ---------- TABLE 1: equipment ----------
CREATE TABLE IF NOT EXISTS public.equipment (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT NOT NULL,
  category      TEXT NOT NULL,
  asset_code    TEXT UNIQUE NOT NULL,
  condition     TEXT NOT NULL DEFAULT 'Good'
                CHECK (condition IN ('Good', 'Fair', 'For Repair')),
  availability  TEXT NOT NULL DEFAULT 'Available'
                CHECK (availability IN ('Available', 'Borrowed')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------- TABLE 2: borrow_transactions ----------
CREATE TABLE IF NOT EXISTS public.borrow_transactions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id  BIGINT NOT NULL REFERENCES public.equipment(id) ON DELETE RESTRICT,
  borrower_name TEXT NOT NULL,
  borrower_type TEXT NOT NULL
                CHECK (borrower_type IN ('Student', 'Faculty', 'Staff')),
  department    TEXT NOT NULL,
  date_borrowed DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date      DATE NOT NULL,
  date_returned DATE,
  claim_date    TIMESTAMPTZ,
  status        TEXT NOT NULL DEFAULT 'Pending'
                CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Borrowed', 'Returned', 'Overdue', 'Cancelled')),
  user_id       UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT due_date_not_before_borrow CHECK (due_date >= date_borrowed)
);

-- Allow new 7 statuses
ALTER TABLE public.borrow_transactions DROP CONSTRAINT IF EXISTS borrow_transactions_status_check;
ALTER TABLE public.borrow_transactions ADD CONSTRAINT borrow_transactions_status_check
  CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Borrowed', 'Returned', 'Overdue', 'Cancelled'));

CREATE INDEX IF NOT EXISTS idx_equipment_name   ON public.equipment (equipment_name);
CREATE INDEX IF NOT EXISTS idx_equipment_avail  ON public.equipment (availability);
CREATE INDEX IF NOT EXISTS idx_txn_borrower     ON public.borrow_transactions (borrower_name);
CREATE INDEX IF NOT EXISTS idx_txn_status       ON public.borrow_transactions (status);
CREATE INDEX IF NOT EXISTS idx_txn_equipment    ON public.borrow_transactions (equipment_id);

-- ---------- TABLE 3: audit_logs (Lab 4) ----------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action          TEXT NOT NULL,
  target_table    TEXT NOT NULL,
  target_id       BIGINT,
  details         TEXT DEFAULT '',
  performed_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  performed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_action ON public.audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_time   ON public.audit_logs (performed_at DESC);

-- ---------- ROW LEVEL SECURITY ----------
ALTER TABLE public.equipment           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.borrow_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs          ENABLE ROW LEVEL SECURITY;

-- Equipment RLS (Only Officer/Admin can manage)
DROP POLICY IF EXISTS "equipment_select_authed"  ON public.equipment;
DROP POLICY IF EXISTS "equipment_insert_officer" ON public.equipment;
DROP POLICY IF EXISTS "equipment_update_officer" ON public.equipment;
DROP POLICY IF EXISTS "equipment_delete_officer" ON public.equipment;

CREATE POLICY "equipment_select_authed" ON public.equipment FOR SELECT TO authenticated USING (true);
CREATE POLICY "equipment_insert_officer" ON public.equipment FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('officer', 'administrator')));
CREATE POLICY "equipment_update_officer" ON public.equipment FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('officer', 'administrator')));
CREATE POLICY "equipment_delete_officer" ON public.equipment FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('officer', 'administrator')));

-- Transactions RLS (Everyone can select/insert, but restricted by UI and Functions)
DROP POLICY IF EXISTS "txn_select_authed" ON public.borrow_transactions;
DROP POLICY IF EXISTS "txn_insert_authed" ON public.borrow_transactions;
DROP POLICY IF EXISTS "txn_update_authed" ON public.borrow_transactions;
DROP POLICY IF EXISTS "txn_delete_authed" ON public.borrow_transactions;

CREATE POLICY "txn_select_authed" ON public.borrow_transactions FOR SELECT TO authenticated USING (true);
CREATE POLICY "txn_insert_authed" ON public.borrow_transactions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "txn_update_authed" ON public.borrow_transactions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "txn_delete_authed" ON public.borrow_transactions FOR DELETE TO authenticated USING (true);

-- Audit Logs RLS (Admin only to view)
DROP POLICY IF EXISTS "audit_select_admin" ON public.audit_logs;
DROP POLICY IF EXISTS "audit_insert_authed" ON public.audit_logs;
CREATE POLICY "audit_select_admin" ON public.audit_logs FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'administrator'));
CREATE POLICY "audit_insert_authed" ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (true);

-- ---------- HELPER: log_audit ----------
CREATE OR REPLACE FUNCTION public.log_audit(p_action TEXT, p_target_table TEXT, p_target_id BIGINT, p_details TEXT DEFAULT '') 
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.audit_logs (action, target_table, target_id, details, performed_by)
  VALUES (p_action, p_target_table, p_target_id, p_details, auth.uid());
END;
$$;

-- ---------- BUSINESS LOGIC FUNCTIONS ----------

-- 1. Record Borrowing (Pending)
CREATE OR REPLACE FUNCTION public.record_borrow(
  p_equipment_id BIGINT, p_borrower_name TEXT, p_borrower_type TEXT, p_department TEXT, p_date_borrowed DATE, p_due_date DATE
) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_id BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.equipment WHERE id = p_equipment_id AND availability = 'Available') THEN
    RAISE EXCEPTION 'BR-03: Only available equipment may be borrowed.';
  END IF;
  IF p_date_borrowed > p_due_date THEN
    RAISE EXCEPTION 'BR-05: Due date cannot be earlier than the borrowing date.';
  END IF;

  INSERT INTO public.borrow_transactions
    (equipment_id, borrower_name, borrower_type, department, date_borrowed, due_date, status, user_id)
  VALUES
    (p_equipment_id, p_borrower_name, p_borrower_type, p_department, p_date_borrowed, p_due_date, 'Pending', auth.uid())
  RETURNING id INTO v_id;

  PERFORM public.log_audit('SUBMIT', 'borrow_transactions', v_id, 'Request submitted for equipment ' || p_equipment_id);
  RETURN v_id;
END;
$$;

-- 2. Approve Borrow (Pending -> Approved)
CREATE OR REPLACE FUNCTION public.approve_borrow(p_txn_id BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('officer', 'administrator')) THEN
    RAISE EXCEPTION 'Only officers or admins can approve requests.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.borrow_transactions WHERE id = p_txn_id AND status = 'Pending') THEN
    RAISE EXCEPTION 'Only pending requests can be approved.';
  END IF;
  
  UPDATE public.borrow_transactions SET status = 'Approved' WHERE id = p_txn_id;
  PERFORM public.log_audit('APPROVE', 'borrow_transactions', p_txn_id, 'Request approved.');
END;
$$;

-- 3. Reject Borrow (Pending -> Rejected)
CREATE OR REPLACE FUNCTION public.reject_borrow(p_txn_id BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('officer', 'administrator')) THEN
    RAISE EXCEPTION 'Only officers or admins can reject requests.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.borrow_transactions WHERE id = p_txn_id AND status = 'Pending') THEN
    RAISE EXCEPTION 'Only pending requests can be rejected.';
  END IF;

  UPDATE public.borrow_transactions SET status = 'Rejected' WHERE id = p_txn_id;
  PERFORM public.log_audit('REJECT', 'borrow_transactions', p_txn_id, 'Request rejected.');
END;
$$;

-- 4. Cancel Request (Borrower: Pending -> Cancelled)
CREATE OR REPLACE FUNCTION public.cancel_borrow(p_txn_id BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_user UUID; v_status TEXT;
BEGIN
  SELECT user_id, status INTO v_user, v_status FROM public.borrow_transactions WHERE id = p_txn_id;
  IF v_user <> auth.uid() THEN RAISE EXCEPTION 'You can only cancel your own requests.'; END IF;
  IF v_status <> 'Pending' THEN RAISE EXCEPTION 'Only pending requests can be cancelled.'; END IF;

  UPDATE public.borrow_transactions SET status = 'Cancelled' WHERE id = p_txn_id;
  PERFORM public.log_audit('CANCEL', 'borrow_transactions', p_txn_id, 'Request cancelled by borrower.');
END;
$$;

-- 5. Claim Equipment (Approved -> Borrowed)
CREATE OR REPLACE FUNCTION public.claim_equipment(p_txn_id BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_equipment_id BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('officer', 'administrator')) THEN
    RAISE EXCEPTION 'Only officers can mark equipment as claimed/borrowed.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.borrow_transactions WHERE id = p_txn_id AND status = 'Approved') THEN
    RAISE EXCEPTION 'Only approved requests can be claimed.';
  END IF;

  SELECT equipment_id INTO v_equipment_id FROM public.borrow_transactions WHERE id = p_txn_id;
  
  -- Prevent claiming if equipment is currently unavailable (e.g. someone else borrowed it)
  IF NOT EXISTS (SELECT 1 FROM public.equipment WHERE id = v_equipment_id AND availability = 'Available') THEN
    RAISE EXCEPTION 'Equipment is currently unavailable. Wait for return or reject this request.';
  END IF;

  UPDATE public.borrow_transactions SET status = 'Borrowed', claim_date = NOW() WHERE id = p_txn_id;
  UPDATE public.equipment SET availability = 'Borrowed' WHERE id = v_equipment_id;
  
  PERFORM public.log_audit('STATUS_CHANGE', 'borrow_transactions', p_txn_id, 'Equipment claimed by borrower.');
END;
$$;

-- 6. Return Equipment (Borrowed/Overdue -> Returned)
CREATE OR REPLACE FUNCTION public.return_equipment(p_txn_id BIGINT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_equipment_id BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('officer', 'administrator')) THEN
    RAISE EXCEPTION 'Only officers can process returns.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.borrow_transactions WHERE id = p_txn_id AND status IN ('Borrowed', 'Overdue')) THEN
    RAISE EXCEPTION 'Only borrowed or overdue equipment can be returned.';
  END IF;

  SELECT equipment_id INTO v_equipment_id FROM public.borrow_transactions WHERE id = p_txn_id;

  UPDATE public.borrow_transactions SET status = 'Returned', date_returned = CURRENT_DATE WHERE id = p_txn_id;
  UPDATE public.equipment SET availability = 'Available' WHERE id = v_equipment_id;
  
  PERFORM public.log_audit('COMPLETE', 'borrow_transactions', p_txn_id, 'Equipment returned.');
END;
$$;

GRANT EXECUTE ON FUNCTION public.log_audit(TEXT, TEXT, BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_borrow(BIGINT, TEXT, TEXT, TEXT, DATE, DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_borrow(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_borrow(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_borrow(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_equipment(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.return_equipment(BIGINT) TO authenticated;