-- ============================================================
-- Supabase Schema  |  Online Equipment Borrowing & Return
-- Monitoring System  |  SAD-EquipmentBorrowing-Moreno
-- Run this in: Supabase Dashboard > SQL Editor > New query
-- ============================================================

-- ---------- TABLE 1: equipment ----------
CREATE TABLE IF NOT EXISTS public.equipment (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT NOT NULL,
  category      TEXT NOT NULL,
  asset_code    TEXT UNIQUE NOT NULL,
  condition     TEXT NOT NULL DEFAULT 'Good'
                CHECK (condition IN ('Good', 'Fair', 'For Repair')),
  availability  TEXT NOT NULL DEFAULT 'Available'
                CHECK (availability IN ('Available', 'Borrowed')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------- TABLE 2: borrow_transactions ----------
CREATE TABLE IF NOT EXISTS public.borrow_transactions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id  BIGINT NOT NULL REFERENCES public.equipment(id) ON DELETE RESTRICT,
  borrower_name TEXT NOT NULL,
  borrower_type TEXT NOT NULL
                CHECK (borrower_type IN ('Student', 'Faculty', 'Staff')),
  department    TEXT NOT NULL,
  date_borrowed DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date      DATE NOT NULL,
  date_returned DATE,
  claim_date    TIMESTAMPTZ,
  status        TEXT NOT NULL DEFAULT 'Pending'
                CHECK (status IN ('Pending', 'Borrowed', 'Returned', 'Overdue', 'Rejected')),
  user_id       UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT due_date_not_before_borrow CHECK (due_date >= date_borrowed)
);

-- Useful indexes for search / filter
CREATE INDEX IF NOT EXISTS idx_equipment_name   ON public.equipment (equipment_name);
CREATE INDEX IF NOT EXISTS idx_equipment_avail  ON public.equipment (availability);
CREATE INDEX IF NOT EXISTS idx_txn_borrower     ON public.borrow_transactions (borrower_name);
CREATE INDEX IF NOT EXISTS idx_txn_status       ON public.borrow_transactions (status);
CREATE INDEX IF NOT EXISTS idx_txn_equipment    ON public.borrow_transactions (equipment_id);

-- Allow the Pending / Rejected statuses even when the table already exists
ALTER TABLE public.borrow_transactions DROP CONSTRAINT IF EXISTS borrow_transactions_status_check;
ALTER TABLE public.borrow_transactions
  ADD CONSTRAINT borrow_transactions_status_check
  CHECK (status IN ('Pending', 'Borrowed', 'Returned', 'Overdue', 'Rejected'));

-- Claimed date+time column (set when an Officer approves/claimes the item)
ALTER TABLE public.borrow_transactions ADD COLUMN IF NOT EXISTS claim_date TIMESTAMPTZ;

-- ---------- ROW LEVEL SECURITY ----------
ALTER TABLE public.equipment           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.borrow_transactions ENABLE ROW LEVEL SECURITY;

-- Only authenticated users can manage the tables (BR-11)
DROP POLICY IF EXISTS "equipment_select_authed"  ON public.equipment;
DROP POLICY IF EXISTS "equipment_insert_authed"  ON public.equipment;
DROP POLICY IF EXISTS "equipment_update_authed"  ON public.equipment;
DROP POLICY IF EXISTS "equipment_delete_authed"  ON public.equipment;
DROP POLICY IF EXISTS "txn_select_authed"        ON public.borrow_transactions;
DROP POLICY IF EXISTS "txn_insert_authed"        ON public.borrow_transactions;
DROP POLICY IF EXISTS "txn_update_authed"        ON public.borrow_transactions;
DROP POLICY IF EXISTS "txn_delete_authed"        ON public.borrow_transactions;

CREATE POLICY "equipment_select_authed" ON public.equipment FOR SELECT
  TO authenticated USING (true);
-- Only Officers can insert / update / delete equipment (Borrowers view only).
DROP POLICY IF EXISTS "equipment_insert_officer" ON public.equipment;
DROP POLICY IF EXISTS "equipment_update_officer" ON public.equipment;
DROP POLICY IF EXISTS "equipment_delete_officer" ON public.equipment;

CREATE POLICY "equipment_insert_officer" ON public.equipment FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'officer'
  ));
CREATE POLICY "equipment_update_officer" ON public.equipment FOR UPDATE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'officer'
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'officer'
  ));
CREATE POLICY "equipment_delete_officer" ON public.equipment FOR DELETE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'officer'
  ));

CREATE POLICY "txn_select_authed" ON public.borrow_transactions FOR SELECT
  TO authenticated USING (true);
CREATE POLICY "txn_insert_authed" ON public.borrow_transactions FOR INSERT
  TO authenticated WITH CHECK (true);
CREATE POLICY "txn_update_authed" ON public.borrow_transactions FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "txn_delete_authed" ON public.borrow_transactions FOR DELETE
  TO authenticated USING (true);

-- Row-level trigger policy helper for RLS: store the logged-in user
-- (The application already sets user_id = auth.uid() on INSERT.)

-- ---------- PROFILES / ROLES (Borrower vs. Officer) ----------
CREATE TABLE IF NOT EXISTS public.profiles (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL DEFAULT 'borrower'
             CHECK (role IN ('borrower', 'officer')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_authed" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own"   ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own"   ON public.profiles;

CREATE POLICY "profiles_select_authed" ON public.profiles FOR SELECT
  TO authenticated USING (true);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;

-- ---------- APPROVE borrowing (Officer) ----------
CREATE OR REPLACE FUNCTION public.approve_borrow(p_txn_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_equipment_id BIGINT;
BEGIN
  -- Role check: only Officers may approve borrow requests
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'officer'
  ) THEN
    RAISE EXCEPTION 'Only officers can approve borrow requests.';
  END IF;

  -- Only a Pending request can be approved (BR-07)
  IF NOT EXISTS (
    SELECT 1 FROM public.borrow_transactions
    WHERE id = p_txn_id AND status = 'Pending'
  ) THEN
    RAISE EXCEPTION 'Only pending borrow requests can be approved.';
  END IF;

  SELECT equipment_id INTO v_equipment_id
  FROM public.borrow_transactions WHERE id = p_txn_id;

  UPDATE public.borrow_transactions
     SET status = 'Borrowed', claim_date = NOW()
   WHERE id = p_txn_id;

  -- BR-07: Borrowed equipment becomes unavailable.
  UPDATE public.equipment SET availability = 'Borrowed' WHERE id = v_equipment_id;
END;
$$;

-- ---------- REJECT borrowing request (Officer) ----------
CREATE OR REPLACE FUNCTION public.reject_borrow(p_txn_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Role check: only Officers may reject requests
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'officer'
  ) THEN
    RAISE EXCEPTION 'Only officers can reject borrow requests.';
  END IF;

  -- Only a Pending request can be rejected
  IF NOT EXISTS (
    SELECT 1 FROM public.borrow_transactions
    WHERE id = p_txn_id AND status = 'Pending'
  ) THEN
    RAISE EXCEPTION 'Only pending borrow requests can be rejected.';
  END IF;

  -- Equipment was never marked Borrowed; only the status changes
  UPDATE public.borrow_transactions SET status = 'Rejected' WHERE id = p_txn_id;
END;
$$;

-- ---------- Atomic business-logic functions ----------

-- Records a borrowing transaction (BR-03, BR-05, BR-06, BR-07)
CREATE OR REPLACE FUNCTION public.record_borrow(
  p_equipment_id BIGINT,
  p_borrower_name TEXT,
  p_borrower_type TEXT,
  p_department TEXT,
  p_date_borrowed DATE,
  p_due_date DATE
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_id BIGINT;
BEGIN
  -- BR-03: Only available equipment may be borrowed.
  IF NOT EXISTS (
    SELECT 1 FROM public.equipment
    WHERE id = p_equipment_id AND availability = 'Available'
  ) THEN
    RAISE EXCEPTION 'BR-03: Only available equipment may be borrowed.';
  END IF;

  -- BR-05: Due date cannot be earlier than the borrowing date.
  IF p_date_borrowed > p_due_date THEN
    RAISE EXCEPTION 'BR-05: Due date cannot be earlier than the borrowing date.';
  END IF;

  -- Insert transaction with Pending status (BR-06). Equipment stays
  -- Available until an Officer approves the request (approve_borrow).
  INSERT INTO public.borrow_transactions
    (equipment_id, borrower_name, borrower_type, department, date_borrowed, due_date, status, user_id)
  VALUES
    (p_equipment_id, p_borrower_name, p_borrower_type, p_department, p_date_borrowed, p_due_date, 'Pending', auth.uid())
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

-- Returns equipment (BR-08, BR-12)
CREATE OR REPLACE FUNCTION public.return_equipment(p_txn_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_equipment_id BIGINT;
BEGIN
  -- BR-12: Only approved transactions (Borrowed/Overdue) can be returned.
  IF NOT EXISTS (
    SELECT 1 FROM public.borrow_transactions
    WHERE id = p_txn_id AND status IN ('Borrowed', 'Overdue')
  ) THEN
    RAISE EXCEPTION 'BR-12: Only approved (Borrowed/Overdue) transactions can be returned.';
  END IF;

  SELECT equipment_id INTO v_equipment_id
  FROM public.borrow_transactions WHERE id = p_txn_id;

  -- Record return date and update status (BR-08)
  UPDATE public.borrow_transactions
     SET status = 'Returned', date_returned = CURRENT_DATE
   WHERE id = p_txn_id;

  -- Equipment becomes available again (BR-08)
  UPDATE public.equipment SET availability = 'Available' WHERE id = v_equipment_id;
END;
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.record_borrow(BIGINT, TEXT, TEXT, TEXT, DATE, DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_borrow(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_borrow(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.return_equipment(BIGINT) TO authenticated;

-- ---------- Overdue helper ----------
-- The application computes "Overdue" in JavaScript when displaying records
-- (per the lab: IF current date > due date AND status != 'Returned' THEN Overdue).
-- Optionally run this statement to mark overdue records in the database:
-- UPDATE public.borrow_transactions
--    SET status = 'Overdue'
--  WHERE status != 'Returned' AND due_date < CURRENT_DATE;